[package]
name = "Zarchan"
version = "0.1.0"
authors = ["Austin Carrig <austincarrig@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.25.4"

[[bin]]
name = "zarchan"
path = "src/zarchan.rs"